config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  use_doorkeeper do
    controllers :applications => 'oauth/applications'
  end

  get 'home/index'
  root 'home#gate'
  get '/me' => 'application#me'
  get 'password_resets/new'
  get 'password_resets/cooperator_edit'
  post 'user/login' => 'sessions#create'
  delete 'user/logout' => 'sessions#destroy'

  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]

  resources :users do
    collection do
      get :add
    end
    resources :access, only: [:update, :edit] do
      member do
        get 'disassociate'
        get 'associate'
      end
    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :relationships, foreign_key: 'user_id', dependent: :destroy
  has_many :applications, class_name: 'Doorkeeper::Application', through: :relationships, source: :application

  has_many :oauth_applications, class_name: 'Doorkeeper::Application', dependent: :destroy, foreign_key: :developer_id

  has_many :accesses, dependent: :destroy
  mount_uploader :icon, IconUploader

  attr_accessor :remember_token, :activation_token, :reset_token
  before_save :downcase_email
  before_create :create_activation_digest

  validates :name, presence: true, length: {maximum: 50}
  validate :icon_size

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: {maximum: 255},
            format: {with: VALID_EMAIL_REGEX},
            uniqueness: {case_sensitive: false}

  #1. The ability to save a securely hashed password_digest attribute to the database
  #2. A pair of virtual attributes (password and password_confirmation), including presence validations upon object creation and a validation requiring that they match
  #3. An authenticate method that returns the user when the password is correct (and false otherwise)
  has_secure_password
  # has_secure_password automatically adds an authenticate method to the corresponding model objects.
  # This method determines if a given password is valid for a particular user by computing its digest and comparing the result to password_digest in the database.
  has_paper_trail

  validates :password, presence: true, length: {minimum: 6}, allow_nil: true

  def User.filter_by_type(type)
    User.where("role = :type", type: type)
  end

  def self.certain_roles(str)
    user=[]
    str.split.each do |type|
      User.filter_by_type(type).each do |each_user|
        user<<each_user
      end
    end
    return user
  end

  # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
        BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def User.new_token
    SecureRandom.urlsafe_base64
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def forget
    update_attribute(:remember_digest, nil)
  end

  # Returns true if the given token matches the digest.
  def authenticated?(attribute, token)
    digest = self.send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end

  def create_reset_digest
    self.reset_token = User.new_token
    update_attribute(:reset_digest, User.digest(reset_token))
    update_attribute(:reset_sent_at, Time.zone.now)
  end

  # Sends password reset email.
  def send_password_reset_email
    UserMailer.password_reset(self).deliver_now
  end

  def password_reset_expired?
    reset_sent_at < 2.hours.ago
  end

  def self.filter_by_users
    User.where(:developer => false).where(:admin => false)
  end

  private

  def icon_size
    if icon.size > 2.megabytes
      errors.add(:picture, "should be less than 5MB")
    end
  end

  def downcase_email
    self.email = email.downcase
  end

  # Creates and assigns the activation token and digest.
  def create_activation_digest
    self.activation_token = User.new_token
    self.activation_digest = User.digest(activation_token)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :logged_in, except: [:new, :create]
  before_action :correct_user, only: [:edit, :show, :update, :destroy]
  before_action :logged_as_developer, only: :index

  def show
    @user = User.find_by_id(params[:id])
  end

  def new
    @user=User.new
  end

  def create
    @user = User.new(user_params)
    @user.number= Faker::Number.number(10)
    if @user.save
      UserMailer.account_activation(@user).deliver_now
      redirect_to root_url, flash: {info: "Please check your email to activate your account."}
    else
      flash[:warning] = "Account saved failed, please try it again"
      render 'new'
    end
  end

  def edit
    @user = User.find_by_id(params[:id])
  end

  def update
    if @user.update_attributes(user_params)
      # Handle a successful update.
      redirect_to @user, flash: {:success => "Profile updated"}
    else
      flash[:warning] = "Profile updated failed"
      render 'edit'
    end
  end

  def destroy
    log_out
    Doorkeeper::Application.filter_by_type(@user.role).each do |app|
      app.users.delete(@user)
    end
    @user.destroy
    redirect_to root_url, flash: {success: "User deleted"}
  end


  #----------------------------------------------------------------

  def index
    @application=Doorkeeper::Application.find_by(id: params[:app_id])
    @users=@application.users
  end

  def add
    @application=Doorkeeper::Application.find_by(id: params[:app_id])
    @users=[]
    User.filter_by_users.each do |user|
      if @application.users.find_by(id: user.id).nil?
          @users<<user
      end
    end
    # @application.users
    render "users/index"
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password,
                                 :password_confirmation, :role, :icon, :department, :company, :developer)
  end

  # Confirms a logged-in user.
  def logged_in
    unless logged_in?
      # store_location
      redirect_to root_url, flash: {danger: 'Please log in first'}
    end
  end

  # Confirms the correct user.
  def correct_user
    @user = User.find(params[:id])
    unless current_user?(@user)
      redirect_to user_path(current_user), flash: {:warning => 'You don not have the access to other user except admin'}
    end
  end

  def logged_as_developer
    unless developer_logged_in?
      redirect_to root_url, flash: {danger: 'Please log in as developer first'}
    end
  end

end

app/helpers/users_helper.rb
module UsersHelper

  def gravatar_for(user,size=nil)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end

end

app/views/users/_form.html.erb
<%= form_for @user, html: {class: 'form-horizontal', role: 'form'} do |f| %>
    <%= render 'shared/error_messages', :object => @user %>
    <%= content_tag :div, class: "form-group#{' has-error' if @user.errors[:name].present?}" do %>
        <%= f.label :name, class: 'col-sm-3 control-label' %>
        <div class="col-sm-8">
          <%= f.text_field :name, class: 'form-control' %>
          <%= doorkeeper_errors_for @user, :name %>
        </div>
    <% end %>

    <%= content_tag :div, class: "form-group#{' has-error' if @user.errors[:email].present?}" do %>
        <%= f.label :email, class: 'col-sm-3 control-label' %>
        <div class="col-sm-8">
          <%= f.text_field :email, class: 'form-control' %>
          <%= doorkeeper_errors_for @user, :email %>
        </div>
    <% end %>

    <%= content_tag :div, class: "form-group#{' has-error' if @user.errors[:company].present?}" do %>
        <%= f.label :company, class: 'col-sm-3 control-label' %>
        <div class="col-sm-8">
          <%= f.text_field :company, class: 'form-control' %>
          <%= doorkeeper_errors_for @user, :company %>
        </div>
    <% end %>

    <%= content_tag :div, class: "form-group#{' has-error' if @user.errors[:department].present?}" do %>
        <%= f.label :department, class: 'col-sm-3 control-label' %>
        <div class="col-sm-8">
          <%= f.text_field :department, class: 'form-control' %>
          <%= doorkeeper_errors_for @user, :department %>
        </div>
    <% end %>

    <%= content_tag :div, class: "form-group#{' has-error' if @user.errors[:role].present?}" do %>
        <%= f.label :role, class: 'col-sm-3 control-label' %>
        <div class="col-sm-8">
          <%= f.select :role, options_for_select(['undergraduate', 'master', 'doctor', 'lecturer', 'associate professor', 'professor', 'executive staff']), {}, class: 'form-control' %>
          <%= doorkeeper_errors_for @user, :role %>
        </div>
    <% end %>

    <%= content_tag :div, class: "form-group#{' has-error' if @user.errors[:password].present?}" do %>
        <%= f.label :password, class: 'col-sm-3 control-label' %>
        <div class="col-sm-8">
          <%= f.text_field :password, class: 'form-control' %>
          <%= doorkeeper_errors_for @user, :password %>
        </div>
    <% end %>

    <%= content_tag :div, class: "form-group#{' has-error' if @user.errors[:password_confirmation].present?}" do %>
        <%= f.label :password_confirmation, class: 'col-sm-3 control-label' %>
        <div class="col-sm-8">
          <%= f.text_field :password_confirmation, class: 'form-control' %>
          <%= doorkeeper_errors_for @user, :password_confirmation %>
        </div>
    <% end %>

    <%= content_tag :div, class: "form-group#{' has-error' if @user.errors[:icon].present?}" do %>
        <%= f.label "Profile icon", class: 'col-sm-3 control-label' %>
        <div class="col-sm-5">
          <span class="icon_picture"><%= f.file_field :icon, accept: 'image/jpeg,image/gif,image/png' %></span>
        </div>
    <% end %>


    <%= content_tag :div, class: "form-group#{' has-error' if @user.errors[:developer].present?}" do %>
        <%= f.label :developer, class: 'col-sm-3 control-label' %>
        <div class="col-sm-8">
          <%= f.select :developer, options_for_select(['true', 'false']), {}, class: 'form-control' %>
          <%= doorkeeper_errors_for @user, :developer %>
        </div>
    <% end %>

    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-9">
        <%= f.submit class: "btn btn-success" %>
        <%= link_to "Cancel", @user.new_record? ? root_path : user_path(@user), :class => "btn btn-default" %>
      </div>
    </div>

<% end %>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>

<div class="row">
  <div class="col-sm-3 sidenav">
    <%=render "shared/sidenav"%>
  </div>

  <div class="col-sm-9">
    <h3 class="text-muted">Edit My Profile</h3>
    <hr>

    <ol class="breadcrumb">
      <li><%=link_to "Account "%></a></li>
      <li class="active">Edit Profile</li>
    </ol>
    <hr>

    <%= render "users/form" %>
  </div>

</div>

app/views/users/index.html.erb
<div class="row">
  <div class="col-sm-3 sidenav">
    <%= render "shared/sidenav" %>
  </div>

  <div class="col-sm-9">
    <h3 class="text-muted">Add users to <%= @application.name %></h3>
    <hr>

    <ol class="breadcrumb">
      <li><%= link_to "App List", oauth_applications_path(current_user) %></a></li>
      <li><%= link_to "App #{@application.id}", oauth_application_path(@application) %></a></li>
      <% if params[:action]=='add' %>
          <li class="active">New Users</li>
      <% elsif params[:action]=='index' %>
          <li class="active">All Users</li>
      <% end %>
    </ol>

    <hr>

    <ul class="nav nav-tabs">
      <li class=<%= "active" if params[:action]=='index' %>><%= link_to "All Users", users_path(app_id: @application.id), class: 'btn btn-link' %></li>
      <li class=<%= "active" if params[:action]=='add' %>><%= link_to "New User", add_users_path(app_id: @application.id), class: 'btn btn-link' %></li>
    </ul>

    <br>

    <table class="table table-striped table-hover">
      <thead>
      <tr>
        <th><%= t('.name') %></th>
        <th><%= t('.role') %></th>
        <th><%= t('department') %></th>
        <th></th>
      </tr>
      </thead>
      <tbody>
      <% @users.each do |user| %>
          <tr>
            <td><%= user.name %></td>
            <td><%= user.role %></a></td>
            <td><%= user.department %></a></td>

            <% if params[:action]=='add' %>
                <td><%= link_to "Add", associate_user_access_path(user, @application), method: :get, class: "btn btn-xs btn-success" %></td>
            <% elsif params[:action]=='index' %>
                <td><%= link_to "Manage Access", edit_user_access_path(user, @application), method: :get, class: 'btn btn-xs btn-info' %></td>
                <td><%= link_to "Delete", disassociate_user_access_path(user, @application), method: :get, class: 'btn btn-xs btn-danger' %></td>
            <% end %>

          </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <div class="panel panel-success">
      <div class="panel-heading">
        <h3 class="text-muted">Sign up as new User</h3>
      </div>
      <div class="panel-body">
        <%= render "users/form" %>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>

<div class="row">
  <div class="col-sm-3 sidenav">
    <%= render "shared/sidenav" %>
  </div>

  <div class="col-sm-8 ">
    <h3 class="text-muted">Show Profile</h3>
    <hr>
    <ol class="breadcrumb">
      <li><%= link_to "Account " %></a></li>
      <li class="active">My Profile</li>
    </ol>
    <hr>

    <div class="panel panel-info">
      <div class="panel-heading">
        <h3 class="panel-title"><%= @user.name %></h3>
      </div>
      <div class="panel-body">
        <div class="row">

          <div class="col-md-3 col-lg-3 " align="center">
            <%= image_tag @user.icon.url if @user.icon? %>
          </div>

          <div class=" col-md-9 col-lg-9 ">
            <table class="table table-user-information">
              <tbody>

              <tr>
                <td>Name:</td>
                <td><%= @user.name %></td>
              </tr>

              <% unless developer_logged_in? %>
                  <tr>
                    <td>ID:</td>
                    <td><%= @user.number %></td>
                  </tr>
              <% end %>

              <tr>
                <td>Email:</td>
                <td><%= @user.email %></td>
              </tr>

              <% if developer_logged_in? %>
                  <tr>
                    <td>Company:</td>
                    <td><%= @user.company %></td>
                  </tr>

              <% elsif user_logged_in? %>
                  <tr>
                    <td>Department:</td>
                    <td><%= @user.department %></td>
                  </tr>

                  <tr>
                    <td>Role:</td>
                    <td><%= @user.role %></td>
                  </tr>

              <% end %>

              <tr>
                <td>Account Created:</td>
                <td><%= @user.created_at.to_formatted_s(:long) %></td>
              </tr>

              <tr>
                <td>Account Activated:</td>
                <td><%= @user.activated_at.to_formatted_s(:long) %></td>
              </tr>

              <tr>
                <td>Last Updated:</td>
                <td><%= @user.updated_at.to_formatted_s(:long) %></td>
              </tr>

              </tbody>
            </table>

            <%= button_to "Edit Profile", edit_user_path(@user), method: :get, class: "btn btn-info" %>
            <%= button_to 'Destroy Account!', user_path(@user), class: 'btn btn-danger',
                          :method => :delete, :data => {confirm: 'Are you sure?'} %>
          </div>
        </div>
      </div>
    </div>

  </div>

</div>