config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  use_doorkeeper do
    controllers :applications => 'oauth/applications'
  end

  get 'home/index'
  root 'home#gate'
  get '/me' => 'application#me'
  get 'password_resets/new'
  get 'password_resets/cooperator_edit'
  post 'user/login' => 'sessions#create'
  delete 'user/logout' => 'sessions#destroy'

  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]

  resources :users do
    collection do
      get :add
    end
    resources :access, only: [:update, :edit] do
      member do
        get 'disassociate'
        get 'associate'
      end
    end
  end

end

app/controllers/access_controller.rb
class AccessController < ApplicationController
  include AccessHelper

  before_action :login_as_admin_or_cooperator
  before_action :set_access

  # node2=[1, 8, 5, 9, 1, 7, 4, 7, 3, 1, 9, 7, 2, 10, 9, 8, 10, 5, 2, 8, 8, 9, 4, 1, 5, 9, 4, 5, 9, 6, 3, 9, 4, 1, 3, 8, 6, 7, 9, 4, 4, 5, 6, 9, 8, 5, 3]
  # parent_id2= [1, 18, 15, 19, 181, 187, 184, 157, 153, 151, 159, 197, 192, 1910, 1819, 1818, 18110, 1875, 1872, 1878, 1848, 1849, 1844, 1841, 1575, 1579, 1574, 1535, 1539, 1536, 1513, 1519, 1514, 1591, 1593, 1598, 1596, 1977, 1979, 1974, 1924, 1925, 1926, 19109, 19108, 19105, 19103]

  def edit
    @parsed_array=PortalGate::Parser.path_parse(@access.node, @access.path)
  end

  def associate
    @user.applications<<@application
    @user.accesses.create!(node: [1], path: [1], app_id: @application.id)
    redirect_to users_path(app_id: @application.id),
                flash: {success: 'user has been associated with this app '}
  end

  def disassociate
    @access.destroy
    @user.applications.delete(@application)
    redirect_to users_path(app_id: @application.id),
                flash: {success: 'user has been disassociated with this app '}
  end

  def update
    node, path=reconstruct(access_params)
    if @access.update_attributes(node: node, path: path)
      flash='The changes has been updated'
      redirect_to edit_user_access_path(@user, @application), flash: {success: flash}
    else
      flash = 'Fail to update changes, please try it again '
      redirect_to edit_user_access_path(@user, @application), flash: {danger: flash}
    end
  end

  private

  def access_params
    params.require(:access).permit(:node, :path)
  end

  def login_as_admin_or_cooperator
    if !admin_logged_in? && !developer_logged_in?
        redirect_to root_url, flash: {danger: 'You have to login as admin or cooperator'}
    end
  end

  def set_access
    @user=User.find_by(id: params[:user_id])
    @application=Doorkeeper::Application.find_by(id: params[:id])
    @access=@user.accesses.find_by(app_id: params[:id])
  end

end

app/helpers/access_helper.rb
require "portal_gate/parser"

module AccessHelper

  def reconstruct(access_params)

    #把node由String转为数组
    node=access_params[:node].split(' ').collect! { |n| n.to_i }

    #把path由String转为数组
    path=[]
    access_params[:path].scan(/\[(.*?)\]/).flatten.each do |item|
      path<<item.split(',').collect! { |n| n.to_i }
    end

    #把path和node结合
    path.each_with_index do |sub_array, index|
      sub_array<<node[index]
    end

    #把path中的数组变为数字(integer)表示
    full_path=[]
    path.each do |sub_array|
      full_path<<sub_array.join('').to_i
    end

    return node, full_path
  end
end

app/views/access/_node.html.erb
<%
  results=PortalGate::Parser.default_traversal(path, parsed_array)
  #next_path储存下一级的path
  next_path=Array.new(path)
  #temp_path储存现在的path,便于后面还原已经改变的next_path
  temp_path=Array.new(path)
  display_info={
      1 => 'Navbar',
      2 => 'Sidebar',
      3 => 'Block'
  }

  #在距离叶节点还有一级的地方就不要再render了,不然results会为[ ]
  #ruby是对象传递,两个数组不能直接等于连接,不然一个修改了,另外一个也要跟着修改
%>

<ul>
  <% results.each do |show| %>
      <li>
        <%= display_info[temp_path.count] -%> <%= show -%> <%= temp_path -%>
        <% if !PortalGate::Parser.default_traversal(next_path<<show, parsed_array).nil? %>
            <%= render 'node', path: next_path,parsed_array: parsed_array %>
        <% end %>
        <% next_path=Array.new(temp_path) %>
      </li>
  <% end %>
</ul>

app/views/access/cooperator_edit.html.erb
<div class="row">

  <div class="col-sm-3 sidenav">
    <%= render "cooperators/sidenav" %>
  </div>

  <h3 class="text-muted">Manage Access: <%= @access.resource.name %></h3>
  <hr>

  <div class="col-sm-9">

    <ol class="breadcrumb">
      <li><%= link_to "Applications List", applications_cooperator_path(@cooperator) %></a></li>
      <li><%= link_to "Application #{@application.id} ", oauth_application_path(@application) %></a></li>
      <li><%= link_to "Users List", cooperator_list_users_path %></a></li>
      <li><%= link_to "User #{@user.id}", user_path(@user) %></a></li>
      <li class="active">Access</li>
    </ol>

    <hr>

    <div class="col-sm-6">
      <h4 class="text-muted">Access Tree Diagram</h4>
      <div class="easy-tree">
        <%= content_tag 'ul' do %>
            <%= content_tag('li') do %>
                User 1 [ ]<%= render 'node', path: [1], parsed_array: @parsed_array %>
            <% end %>
        <% end %>
      </div>
    </div>

    <div class="col-sm-6">
      <h4 class="text-muted">Input</h4>

      <div class="well">
        <div class="easy-tree-toolbar">

          <div class="input-group">
            <input type="text" class="form-control" id="disabledInput" disabled>
          <span class="input-group-btn">
            <button type="button" class="btn btn-success confirm disabled">Confirm</button>
            <button type="button" class="btn btn-default cancel disabled">Cancel</button>
          </span>
          </div>
          <br>

          <div class="form-group">
            <div class="create">
              <button class="btn btn-success disabled">
                <span class="glyphicon glyphicon-plus"></span>Add Node
              </button>
            </div>
          </div>

          <div class="form-group">
            <div class="edit">
              <button class="btn btn-primary disabled">
                <span class="glyphicon glyphicon-edit"></span>Edit Node
              </button>
            </div>
          </div>

          <div class="form-group">
            <div class="remove">
              <button class="btn btn-danger disabled">
                <span class="glyphicon glyphicon-remove"></span>Delete Node
              </button>
            </div>
          </div>

        </div>
      </div>

      <button type="button" class="btn btn-primary" id="commit">Push Changes</button>
      <button type="button" class="btn btn-info" id="show_form">Show Detail</button>
      <button type="button" id="hidden_form" class="btn btn-warning hidden">Hide Detail</button>

      <div id="form" class="hidden">
        <h3 class="text-muted">Access Data Array</h3>
        <%= form_for @access, url: user_access_path(@user, @application),
                     html: {id: 'tree_form', class: 'form-horizontal', role: 'form'} do |f| %>
            <div class="form-group">
              <%= f.label :node, class: "control-label col-sm-2" %>
              <div class="col-sm-10">
                <%= f.text_area :node, class: "form-control", id: "access_node_update", rows: "5" %>
              </div>
            </div>

            <div class="form-group">
              <%= f.label :path, class: "control-label col-sm-2" %>
              <div class="col-sm-10">
                <%= f.text_area :path, class: "form-control", id: "access_path_update", rows: "8" %>
              </div>
            </div>

        <% end %>
      </div>

    </div>
  </div>
</div>

<script type="text/javascript">
  (function ($) {
    function init() {
      $('.easy-tree').EasyTree({});
    }

    window.onload = init();
  })(jQuery);

  $("#commit").click(function (e) {
    e.preventDefault();
    var content = $('.easy-tree').find('a');
    var filter = content.text().replace(/[\r\n\s]/g, "").replace(/[A-Za-z]/g, "");

    var new_path = filter.match(/\[(.*?)\]/g);
    var node = filter.replace(/\[(.*?)\]/g, " ");

    document.getElementById("access_node_update").value = node;
    document.getElementById("access_path_update").value = new_path;
    document.getElementById('tree_form').submit();
  });


  $("#show_form").click(function (e) {
    $('#form').removeClass("hidden");
    $(this).addClass("hidden");
    $('#hidden_form').removeClass("hidden");
  });

  $("#hidden_form").click(function (e) {
    $('#form').addClass("hidden");
    $(this).addClass("hidden");
    $('#show_form').removeClass("hidden");
  });


  //    var array = [];
  //    for (var key in text) {
  //      if (text[key] != "-") {
  //        array.push(text[key])
  //      }
  //    }

  //    alert(text);


  //    for (var i = 0; i < array.length; i++) {
  //      if(array[i].match(/^[A-Za-z]/)){
  //        array.splice(i,1);
  //      }
  //    }
  //

  //    newarray=[];
  //    for (var i = 0; i < array.length; i++) {
  //      if(array[i]&&array[i]!=""){
  //        newarray.push(array[i])
  //      }
  //    }


</script>


<!------------------------------------------------------------------------------------------------------------------>

app/views/access/edit.html.erb
<div class="row">

  <div class="col-sm-3 sidenav">
    <%= render "shared/sidenav" %>
  </div>

  <h3 class="text-muted">Manage Access: <%= @access.user.name %></h3>
  <hr>

  <div class="col-sm-9">

    <ol class="breadcrumb">
      <li><%= link_to "Apps List", oauth_applications_path %></a></li>
      <li><%= link_to "Application #{@application.id} ", oauth_application_path(@application) %></a></li>
      <li><%= link_to "Users List", users_path(app_id: @application.id) %></a></li>
      <li><%= link_to "User #{@user.id}", user_path(@user) %></a></li>
      <li class="active">Access</li>
    </ol>

    <hr>

    <div class="col-sm-6">
      <h4 class="text-muted">Access Tree Diagram</h4>
      <div class="easy-tree">
        <%= content_tag 'ul' do %>
            <%= content_tag('li') do %>
                User 1 [ ]<%= render 'node', path: [1], parsed_array: @parsed_array %>
            <% end %>
        <% end %>
      </div>
    </div>

    <div class="col-sm-6">
      <h4 class="text-muted">Input</h4>

      <div class="well">
        <div class="easy-tree-toolbar">

          <div class="input-group">
            <input type="text" class="form-control" id="disabledInput" disabled>
          <span class="input-group-btn">
            <button type="button" class="btn btn-success confirm disabled">Confirm</button>
            <button type="button" class="btn btn-default cancel disabled">Cancel</button>
          </span>
          </div>
          <br>

          <div class="form-group">
            <div class="create">
              <button class="btn btn-success disabled">
                <span class="glyphicon glyphicon-plus"></span>Add Node
              </button>
            </div>
          </div>

          <div class="form-group">
            <div class="edit">
              <button class="btn btn-primary disabled">
                <span class="glyphicon glyphicon-edit"></span>Edit Node
              </button>
            </div>
          </div>

          <div class="form-group">
            <div class="remove">
              <button class="btn btn-danger disabled">
                <span class="glyphicon glyphicon-remove"></span>Delete Node
              </button>
            </div>
          </div>

        </div>
      </div>

      <button type="button" class="btn btn-primary" id="commit">Push Changes</button>
      <button type="button" class="btn btn-info" id="show_form">Show Detail</button>
      <button type="button" id="hidden_form" class="btn btn-warning hidden">Hide Detail</button>

      <div id="form" class="hidden">
        <h3 class="text-muted">Access Data Array</h3>
        <%= form_for @access, url: user_access_path(@user, @application),
                     html: {id: 'tree_form', class: 'form-horizontal', role: 'form'} do |f| %>
            <div class="form-group">
              <%= f.label :node, class: "control-label col-sm-2" %>
              <div class="col-sm-10">
                <%= f.text_area :node, class: "form-control", id: "access_node_update", rows: "5" %>
              </div>
            </div>

            <div class="form-group">
              <%= f.label :path, class: "control-label col-sm-2" %>
              <div class="col-sm-10">
                <%= f.text_area :path, class: "form-control", id: "access_path_update", rows: "8" %>
              </div>
            </div>

        <% end %>
      </div>

    </div>
  </div>
</div>

<script type="text/javascript">
  (function ($) {
    function init() {
      $('.easy-tree').EasyTree({});
    }

    window.onload = init();
  })(jQuery);

  $("#commit").click(function (e) {
    e.preventDefault();
    var content = $('.easy-tree').find('a');
    var filter = content.text().replace(/[\r\n\s]/g, "").replace(/[A-Za-z]/g, "");

    var new_path = filter.match(/\[(.*?)\]/g);
    var node = filter.replace(/\[(.*?)\]/g, " ");

    document.getElementById("access_node_update").value = node;
    document.getElementById("access_path_update").value = new_path;
    document.getElementById('tree_form').submit();
  });


  $("#show_form").click(function (e) {
    $('#form').removeClass("hidden");
    $(this).addClass("hidden");
    $('#hidden_form').removeClass("hidden");
  });

  $("#hidden_form").click(function (e) {
    $('#form').addClass("hidden");
    $(this).addClass("hidden");
    $('#show_form').removeClass("hidden");
  });


  //    var array = [];
  //    for (var key in text) {
  //      if (text[key] != "-") {
  //        array.push(text[key])
  //      }
  //    }

  //    alert(text);


  //    for (var i = 0; i < array.length; i++) {
  //      if(array[i].match(/^[A-Za-z]/)){
  //        array.splice(i,1);
  //      }
  //    }
  //

  //    newarray=[];
  //    for (var i = 0; i < array.length; i++) {
  //      if(array[i]&&array[i]!=""){
  //        newarray.push(array[i])
  //      }
  //    }


</script>


<!------------------------------------------------------------------------------------------------------------------>