config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  use_doorkeeper do
    controllers :applications => 'oauth/applications'
  end

  get 'home/index'
  root 'home#gate'
  get '/me' => 'application#me'
  get 'password_resets/new'
  get 'password_resets/cooperator_edit'
  post 'user/login' => 'sessions#create'
  delete 'user/logout' => 'sessions#destroy'

  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]

  resources :users do
    collection do
      get :add
    end
    resources :access, only: [:update, :edit] do
      member do
        get 'disassociate'
        get 'associate'
      end
    end
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  include HomeHelper

  def index
    if admin_logged_in?
      @application=Doorkeeper::Application.all
    elsif developer_logged_in?
      @application=current_user.oauth_applications
    elsif logged_in?
      @application=current_user.applications
    else
      redirect_to root_url, flash: {danger: 'Please log in first'}
    end
  end

  def gate
    @application=Doorkeeper::Application.all
  end

end

app/helpers/home_helper.rb
module HomeHelper

  APP_MAP={
      1=>"Discipline Consititution",
      2=>"Teacher Management",
      3=>"Recruitment Management",
      4=>"Registration Center",
      5=>"Registration Management",
      6=>"Status Management",
      7=>"Course Selection",
      8=>"Academic Affairs",
      9=>"Student Activity",
      10=>"Training Guidance",
      11=>"Academic Degree",
      12=>"Employment Management",
      13=>"Alumni Managemen",
      14=>"Accomodation Management",
      15=>"Course Resources",
      16=>"Cloud Classroom"
  }

  def convert_list_to_array(application)
    list=[]
    application.each_with_index { |item, key|
      list<<application[key].id
    }
    return list
  end


  def map_app

  end


end

app/views/home/_login.html.erb
<% provide(:title, "Uers Log in") %>
<h3 class="text-muted">Users Log in</h3>

<div class="well">
  <%= form_for(:session, url: user_login_path) do |f| %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <text color="blue"><%= link_to "(forgot password?)", new_password_reset_path,{:style=>'color:red;'}  %></text>
      <%= f.password_field :password, class: 'form-control' %>

      <div class="col-sm-offset-1">
        <%= f.label :remember_me, class: "checkbox inline" do %>
            <%= f.check_box :remember_me %>
            <span class="small">Remember me on this computer</span>
        <% end %>
      </div>

      <%= f.submit "Log in", class: "btn btn-primary" %>
  <% end %>
  <br>
  New user? <%= link_to "Sign up now!", new_user_path,{:style=>'color:green;'} %>

</div>

app/views/home/_new_user.html.erb
<% provide(:title, "Uers Log in") %>
<h3 class="text-muted">Users Log in</h3>

<div class="well">
  <%= form_for(:session, url: user_login_path) do |f| %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <text color="blue"><%= link_to "(forgot password?)", new_password_reset_path,{:style=>'color:red;'}  %></text>
      <%= f.password_field :password, class: 'form-control' %>

      <div class="col-sm-offset-1">
        <%= f.label :remember_me, class: "checkbox inline" do %>
            <%= f.check_box :remember_me %>
            <span class="small">Remember me on this computer</span>
        <% end %>
      </div>

      <%= f.submit "Log in", class: "btn btn-primary" %>
  <% end %>
  <br>
  New user? <%= link_to "Sign up now!", new_user_path,{:style=>'color:green;'} %>

</div>

app/views/home/_related_links.html.erb
<div clss="panel panel-default">

  <h3 class="text-muted">Related Links</h3>

  <br>
  <p>
    <span class="	glyphicon glyphicon-link"></span>
    <%= link_to "Ministry of Education of People's Republic of China", "http://www.moe.edu.cn/" %>
  </p>
  
  <p>
    <span class="	glyphicon glyphicon-link"></span>
    <%= link_to "Chiese Society of Academic Degrees And Education", "http://www.csadge.edu.cn/" %><br>
  </p>

  <p>
    <span class="	glyphicon glyphicon-link"></span>
    <%= link_to "National Engineering Doctoral Education", "http://www.meng.edu.cn/" %><br>
  </p>

  <p>
    <span class="	glyphicon glyphicon-link"></span>
    <%= link_to "National Library of China", "http://www.nlc.gov.cn/" %><br>
  </p>

  <p>
    <span class="	glyphicon glyphicon-link"></span>
    <%= link_to "National Library, Chinese Academy of Sicence", "" %><br>
  </p>

  <p>
    <span class="	glyphicon glyphicon-link"></span>
    <%= link_to "Sharing Resources of Science and Technology China", "" %><br>
  </p>

  <hr>

  <h3 class="text-muted">Related Downloads</h3>
  <br>

  <p>
    <span class="	glyphicon glyphicon-cloud-download"></span>
    <%= link_to "Education Cloud Service Guide (Graduate Student)", "http://sep.ucas.ac.cn/resources/doc/User_Service_Guide[YJS].pdf" %>
  </p>

  <p>
    <span class="	glyphicon glyphicon-cloud-download"></span>
    <%= link_to "Education Cloud Service Guide (Bachelar Student)", "http://sep.ucas.ac.cn/resources/doc/User_Service_Guide[BKS].pdf" %>
  </p>

  <p>
    <span class="	glyphicon glyphicon-cloud-download"></span>
    <%= link_to "Education Cloud Service Guide (Teacher)", "http://sep.ucas.ac.cn/resources/doc/User_Service_Guide[JS].pdf" %>
  </p>

  <p>
    <span class="	glyphicon glyphicon-cloud-download"></span>
    <%= link_to "Education Cloud Service Guide (Research Insititude)", "http://inc.ucas.ac.cn/home/info/3a25bf0a-1c49-4c5a-b302-a2103e353a9f" %>
  </p>

  <p>
    <span class="	glyphicon glyphicon-cloud-download"></span>
    <%= link_to "Regulations of the Rights of User", "http://sep.ucas.ac.cn/resources/doc/User_rights_management_regulations[UCAS].pdf" %>
  </p>
  <p>

    <span class="	glyphicon glyphicon-cloud-download"></span>
    <%= link_to "Commom Problems", "http://sep.ucas.ac.cn/resources/doc/SEP_FAQ[UCAS].pdf" %>
  </p>

  <p>
    <span class="	glyphicon glyphicon-cloud-download"></span>
    <%= link_to "Enrollment System Key Driver", "" %>
  </p>


</div>

app/views/home/gate.html.erb
<div class="container">
  <div class="row">
    <div class="container col-sm-8">

      <h3 class="text-muted">Education Management Platform</h3>
      <hr>

      <div class="row">
        <% @application.each do |application| %>
            <div class="container-fluid col-sm-6" style="min-height: 120px;max-height: 120px">
              <div class="container-fluid col-sm-3">
                <br>
                <%= image_tag application.picture.url if application.picture? %>
              </div>
              <div class="container-fluid col-sm-9">
                <h4><%= application.name %></h4>
                <p class="text-muted"><%= truncate(application.description, length: 100) %></p>
                <br>
              </div>
            </div>
        <% end %>

      </div>

    </div>


    <div class="panel panel-default col-sm-4">
      <%= render "login" %>
    </div>

    <div class="panel panel-default col-sm-4">
      <%= render "home/related_links" %>

    </div>
  </div>

</div>

app/views/home/index.html.erb
<% content_for :body_class, "body-background" %>

<% @application.each do |app| %>
    <div class="col-sm-2">
      <div class="icon-container">

        <% if current_user.admin ||current_user.developer %>
            <%= image_tag app.picture.url if app.picture? %>
            <h5 style="color: black"><%= app.name %></h5>
        <% else %>
            <%= link_to app.homepage do %>
                <%= image_tag app.picture.url if app.picture? %>
                <h5 style="color: black"><%= app.name %></h5>
            <% end %>
        <% end %>

      </div>
    </div>
<% end %>