config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  use_doorkeeper do
    controllers :applications => 'oauth/applications'
  end

  get 'home/index'
  root 'home#gate'
  get '/me' => 'application#me'
  get 'password_resets/new'
  get 'password_resets/cooperator_edit'
  post 'user/login' => 'sessions#create'
  delete 'user/logout' => 'sessions#destroy'

  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]

  resources :users do
    collection do
      get :add
    end
    resources :access, only: [:update, :edit] do
      member do
        get 'disassociate'
        get 'associate'
      end
    end
  end

end

app/views/layouts/_content.html.erb
<div class="container">
  <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
        <strong> <%= message %></strong>
      </div>
  <% end %>
</div>

<br>
<div class="container">
<%= yield %>
</div>
<br>

app/views/layouts/_footer.html.erb
<div class="navbar navbar-fixed-bottom">

  <footer class="container-fluid">
    <p>University of Chinese Academy of Sciences Copyright © 2012 UCAS Address:  No.19A Yuquan Road, Beijing 100049, China
    </p>
  </footer>
</div>

app/views/layouts/_global_search.html.erb
<%= form_tag search_users_or_cooperators_path, :method => :get, class: "navbar-form", role: "search" do %>

    <div class="input-group">
      <%= text_field_tag 'query', nil, class: "form-control", placeholder: "Search Event" %>
      <div class="input-group-btn">
        <button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i></button>
      </div>
    </div>

<% end -%>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">

    <div class="navbar-header">
      <a href="<%= root_url %>"><img src=<%= image_path("logo.png") %>></a>
    </div>

    <div class="collapse navbar-collapse">

      <ul class="nav navbar-nav navbar-right">

        <% if admin_logged_in? %>

            <div class="navbar-text">
              <%= current_user.name %>
            </div>

            <li>
              <%= link_to home_index_path do %>
                  <span class="	glyphicon glyphicon-user"></span> Admin
              <% end %>
            </li>

            <li><%= link_to "Dashboard", rails_admin_path %></li>

            <li>
              <%= link_to user_logout_path, method: :delete do %>
                  <span class="	glyphicon glyphicon-off"></span>
              <% end %>
            </li>

        <% elsif developer_logged_in? %>

            <div class="navbar-text">
              <span class="	glyphicon glyphicon-home"></span> <%= current_user.company %>
            </div>

            <div class="navbar-text">
              <span class="	glyphicon glyphicon-user"></span> Developer
            </div>

            <li><%= link_to user_path(current_user) do %>
                  <span class="	glyphicon glyphicon-cog"></span> <%= current_user.name %>
              <% end %>
            </li>

            <li><%= link_to user_logout_path, method: :delete do %>
                  <span class="	glyphicon glyphicon-off"></span>
              <% end %>
            </li>

        <% elsif logged_in? %>

            <div class="navbar-text">
              <span class="	glyphicon glyphicon-home"></span>  <%= current_user.department %>
            </div>

            <div class="navbar-text">
              <span class="	glyphicon glyphicon-user"></span><%= current_user.role %>
            </div>

            <li><%= link_to user_path(current_user) do %>
                  <span class="	glyphicon glyphicon-cog"></span> <%= current_user.name %>
              <% end %>
            </li>

            <li>
              <%= link_to user_logout_path, method: :delete do %>
                  <span class="	glyphicon glyphicon-off"></span>
              <% end %>
            </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>UcasPortal</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  <%= csrf_meta_tags %>
</head>

<body class="<%= yield (:body_class) %>">

<%= render partial: 'layouts/header' %>
<%= render partial: 'layouts/content' %>
<%= render partial: 'layouts/footer' %>

</body>
</html>